[[main]]
  identifier = "xml-builder-docs"
  name = "XML Builder"
  url = "xml-builder-docs"
  weight = 1

[[main]]
  identifier = "xml-sender-docs"
  name = "XML Sender"
  url = "xml-sender-docs"
  weight = 1

[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3